/* (Beta) Export of data model TransportStation of the subject dataModel.Transportation for a PostgreSQL database. Pending translation of enumerations and multityped attributes */
CREATE TYPE TransportStation_installationMode_type AS ENUM ('aerial', 'ground', 'underGround', 'underSea');
CREATE TYPE TransportStation_locationType_type AS ENUM ('0', '1', '2', '3', '4');
CREATE TYPE TransportStation_type AS ENUM ('TransportStation');
CREATE TYPE TransportStation_wheelChairAccessible_type AS ENUM ('0', '1', '2');
CREATE TABLE TransportStation (
  "address" JSON,
  "alternateName" TEXT,
  "architect" TEXT,
  "areaServed" TEXT,
  "commissioningDate" TIMESTAMP,
  "constructionDate" TIMESTAMP,
  "contactPoint" JSON,
  "contractingAuthority" TEXT,
  "contractingCompany" TEXT,
  "currencyAccepted" JSON,
  "dataProvider" TEXT,
  "dateCreated" TIMESTAMP,
  "dateLastReported" TIMESTAMP,
  "dateModified" TIMESTAMP,
  "description" TEXT,
  "dimension" JSON,
  "featuredArtist" JSON,
  "id" TEXT PRIMARY KEY,
  "installationMode" TransportStation_installationMode_type,
  "inventory" JSON,
  "levelId" NUMERIC,
  "location" JSON,
  "locationType" TransportStation_locationType_type,
  "name" TEXT,
  "openingHoursSpecification" JSON,
  "owner" JSON,
  "parentStation" JSON,
  "paymentAccepted" JSON,
  "platformCode" NUMERIC,
  "refPointOfInterest" JSON,
  "seeAlso" JSON,
  "services" JSON,
  "source" TEXT,
  "stationConnected" JSON,
  "stationType" JSON,
  "type" TransportStation_type,
  "webSite" TEXT,
  "wheelChairAccessible" TransportStation_wheelChairAccessible_type,
  "zoneId" TEXT
);