/* (Beta) Export of data model RoadSegment of the subject dataModel.Transportation for a PostgreSQL database. Pending translation of enumerations and multityped attributes */
CREATE TYPE RoadSegment_cyclePathPlacement_type AS ENUM ('BOTH', 'LEFT', 'NOT_AVAILABLE', 'RIGHT');
CREATE TYPE RoadSegment_roadClass_type AS ENUM ('MAJOR_DISTRICT_ROAD', 'MAJOR_CITY_ROAD', 'MINOR_CITY_ROAD', 'NATIONAL_HIGHWAY', 'OTHER_DISTRICT_ROAD', 'OTHER_PUBLIC_ROAD', 'PORT_ROAD', 'PRIVATE_ROAD', 'SERVICE_ROAD', 'STATE_HIGHWAY');
CREATE TYPE RoadSegment_roadWork_type AS ENUM ('COLLAPSE', 'DERAILMENT', 'FIRE', 'FLOOD', 'GASLEAK', 'LANDSLIDE', 'OTHER', 'POWERCUT', 'ROCKFALL', 'SAGGING', 'WATERLEAK');
CREATE TYPE RoadSegment_type AS ENUM ('RoadSegment');
CREATE TABLE RoadSegment (
  "address" JSON,
  "agency_name" TEXT,
  "allowedVehicleType" JSON,
  "alternateName" TEXT,
  "annotations" JSON,
  "areaServed" TEXT,
  "bridgeCount" NUMERIC,
  "carriagewayLength" NUMERIC,
  "carriagewayWidth" NUMERIC,
  "category" JSON,
  "color" TEXT,
  "culvertCount" NUMERIC,
  "cyclePathLeftHeight" NUMERIC,
  "cyclePathLeftWidth" NUMERIC,
  "cyclePathMaterial" TEXT,
  "cyclePathPlacement" RoadSegment_cyclePathPlacement_type,
  "cyclePathRightHeight" NUMERIC,
  "cyclePathRightWidth" NUMERIC,
  "dataDescriptor" JSON,
  "dataProvider" TEXT,
  "dateCreated" TIMESTAMP,
  "dateModified" TIMESTAMP,
  "description" TEXT,
  "endKilometer" NUMERIC,
  "endPoint" JSON,
  "id" TEXT PRIMARY KEY,
  "image" TEXT,
  "laneInfo" JSON,
  "laneUsage" JSON,
  "length" NUMERIC,
  "location" JSON,
  "maximumAllowedHeight" NUMERIC,
  "maximumAllowedSpeed" NUMERIC,
  "maximumAllowedWeight" NUMERIC,
  "maximumAllowedWidth" NUMERIC,
  "medianHeight" NUMERIC,
  "medianLength" NUMERIC,
  "medianWidth" NUMERIC,
  "minimumAllowedSpeed" NUMERIC,
  "municipalityInfo" JSON,
  "name" TEXT,
  "owner" JSON,
  "pedestrianPathLeftHeight" NUMERIC,
  "pedestrianPathLeftWidth" NUMERIC,
  "pedestrianPathMaterial" TEXT,
  "pedestrianPathPlacement" TEXT,
  "pedestrianPathRightHeight" NUMERIC,
  "pedestrianPathRightWidth" NUMERIC,
  "refRoad" JSON,
  "rightOfWayWidth" NUMERIC,
  "roadClass" RoadSegment_roadClass_type,
  "roadDirection" TEXT,
  "roadId" TEXT,
  "roadMaterial" TEXT,
  "roadName" TEXT,
  "roadWork" RoadSegment_roadWork_type,
  "seeAlso" JSON,
  "source" TEXT,
  "startKilometer" NUMERIC,
  "startPoint" JSON,
  "status" TEXT,
  "statusDescription" TEXT,
  "totalCyclePathWidth" NUMERIC,
  "totalLaneNumber" NUMERIC,
  "totalPedestrianPathLength" NUMERIC,
  "totalPedestrianPathWidth" NUMERIC,
  "type" RoadSegment_type,
  "width" NUMERIC
);